<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Mata</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mata</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mata</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.mata</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mata</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mata</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.compound.mata</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cdq_string_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.mata</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.mata</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.mata</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cb_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.mata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^$\s])(version|pragma|if|else|for|while|do|break|continue|goto|return)(?=\s)</string>
			<key>name</key>
			<string>keyword.control.mata</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.eltype.mata</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.orgtype.mata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(transmorphic|string|numeric|real|complex|(pointer(\([^)]+\))?))\s+(matrix|vector|rowvector|colvector|scalar)\b</string>
			<key>name</key>
			<string>storage.type.mata</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>need to end with whitespace character here or last group doesn't match</string>
			<key>match</key>
			<string>\b(transmorphic|string|numeric|real|complex|(pointer(\([^)]+\))?))\s</string>
			<key>name</key>
			<string>storage.type.eltype.mata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(matrix|vector|rowvector|colvector|scalar)\b</string>
			<key>name</key>
			<string>storage.type.orgtype.mata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!|\+\+|\-\-|\&amp;|\'|\?|\\|\:\:|\,|\.\.|\||\=|\=\=|\&gt;\=|\&lt;\=|\&lt;|\&gt;|\!\=|\#|\+|\-|\*|\^|\/</string>
			<key>name</key>
			<string>keyword.operator.mata</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_functions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtin_functions</key>
		<dict>
			<key>match</key>
			<string>(?x)(
                abs|acos|acosh|acosr|ado_fromlchar|ado_intolchar|adosubdir|all|allof|
			  any|anyof|arg|args|ascii|asin|asinh|asinr|assert|asserteq|atan|atan2|
			  atanh|atanr
			)(?=\()</string>
			<key>name</key>
			<string>support.function.builtin.mata</string>
		</dict>
		<key>cb_content</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cb_content</string>
				</dict>
			</array>
		</dict>
		<key>cdq_string_content</key>
		<dict>
			<key>begin</key>
			<string>`"</string>
			<key>end</key>
			<string>"'</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cdq_string_content</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mata</string>
	<key>uuid</key>
	<string>A1B2D6E0-F46E-4C1D-9120-60F1DE74272F</string>
</dict>
</plist>
