<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>do</string>
		<string>ado</string>
		<string>mata</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Stata</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.stata</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`"</string>
			<key>end</key>
			<string>"'</string>
			<key>name</key>
			<string>string.quoted.double.compound.stata</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\*.*$\n?</string>
			<key>name</key>
			<string>comment.line.star.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//[^/].*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>///.*$</string>
			<key>name</key>
			<string>comment.line.triple-slash.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|\^</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.stata</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>match division operator but not path separator</string>
			<key>match</key>
			<string>(?&lt;![a-zA-Z.])/(?![a-zA-Z.]|$)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&amp;|\||!|~</string>
			<key>name</key>
			<string>keyword.operator.logical.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;|&gt;|&lt;\=|&gt;\=|\=\=|!\=|~\=</string>
			<key>name</key>
			<string>keyword.operator.comparison.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.stata</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(while|forv(a|al|alu|alue|alues)?|continue)\b</string>
			<key>name</key>
			<string>keyword.control.flow.stata</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.stata</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.stata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(foreach)\s+[a-zA-Z0-9_]+\s+(in|of loc(a|al)?|of glo(b|ba|bal)?|of var(l|li|lis|list)?|of new(l|li|lis|list)?|of num(l|li|lis|list)?)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.stata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(if|else if|else)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.macro.stata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(gl(o|ob|oba|obal)?|loc(a|al)?|tempvar|tempname|tempfile)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.stata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(sca(l|la|lar)?(\s+de(f|fi|fin|fine)?)?)\s+(?!(drop|dir?|l(i|is|ist)?)\s+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.stata</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.stata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^|:|{|qui(e|et|etl|etly)?\s+|n(o|oi|ois|oisi|oisil|oisily)?\s+)\s*(by(s|so|sor|sort)?)((\s|,)[^:]*)?(?=:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.variable.stata</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^|:|{|qui(e|et|etl|etly)?\s+|n(o|oi|ois|oisi|oisil|oisily)?\s+)\s*((g(e|en|ene|ener|enera|enerat|enerate)?)|replace|egen)\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*mata:?\s*$</string>
			<key>comment</key>
			<string>won't match single-line Mata statements</string>
			<key>end</key>
			<string>^\s*end</string>
			<key>name</key>
			<string>source.stata.embedded.mata</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mata</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.stata</string>
	<key>uuid</key>
	<string>4011DD24-A5DD-4723-AE6B-65042218AB1F</string>
</dict>
</plist>
